// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// vectorSum
double vectorSum(NumericVector x);
RcppExport SEXP _templater_vectorSum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(vectorSum(x));
    return rcpp_result_gen;
END_RCPP
}

RcppExport void mat_mult_iter_c(void *, void *, void *, void *, void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"_templater_vectorSum", (DL_FUNC) &_templater_vectorSum, 1},
    {"mat_mult_iter_c", (DL_FUNC) &mat_mult_iter_c, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_templater(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
