# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Vector Sum
#' 
#' This function sums a vector
#'
#' @param x A numeric vector
#' @export
vectorSum <- function(x) {
    .Call('_templater_vectorSum', PACKAGE = 'templater', x)
}

